// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.
// <auto-generated />
// No style analysis for imported project.

namespace System.Windows.Controls.Samples.SyntaxHighlighting
{
    internal class TextInsertion
    {
        public virtual int Index {get; set; }
        public virtual string Text { get; set; }
        public virtual Scope Scope { get; set; }
    }
}