// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1824:MarkAssembliesWithNeutralResourcesLanguage", Justification = "Not using resources")]
[assembly: SuppressMessage("Microsoft.Design", "CA1060:MovePInvokesToNativeMethodsClass", Scope = "member", Target = "AdvancedDataGridView.TreeGridView+Win32Helper.#SendMessage(System.Runtime.InteropServices.HandleRef,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1060:MovePInvokesToNativeMethodsClass", Scope = "member", Target = "AdvancedDataGridView.TreeGridView+Win32Helper.#SendMessage(System.Runtime.InteropServices.HandleRef,System.Int32,System.IntPtr,System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1060:MovePInvokesToNativeMethodsClass", Scope = "member", Target = "AdvancedDataGridView.TreeGridView+Win32Helper.#PostMessage(System.Runtime.InteropServices.HandleRef,System.Int32,System.IntPtr,System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "AdvancedDataGridView.TreeGridView+Win32Helper.#SendMessage(System.Runtime.InteropServices.HandleRef,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1414:MarkBooleanPInvokeArgumentsWithMarshalAs", Scope = "member", Target = "AdvancedDataGridView.TreeGridView+Win32Helper.#PostMessage(System.Runtime.InteropServices.HandleRef,System.Int32,System.IntPtr,System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "AdvancedDataGridView.CollapsedEventArgs")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "type", Target = "AdvancedDataGridView.CollapsedEventHandler")]
[assembly: SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope = "type", Target = "AdvancedDataGridView.CollapsingEventHandler")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "AdvancedDataGridView.ExpandedEventArgs")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "type", Target = "AdvancedDataGridView.ExpandedEventHandler")]
[assembly: SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope = "type", Target = "AdvancedDataGridView.ExpandingEventHandler")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "AdvancedDataGridView.TreeGridCell.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "glyphHalf", Scope = "member", Target = "AdvancedDataGridView.TreeGridCell.#Paint(System.Drawing.Graphics,System.Drawing.Rectangle,System.Drawing.Rectangle,System.Int32,System.Windows.Forms.DataGridViewElementStates,System.Object,System.Object,System.String,System.Windows.Forms.DataGridViewCellStyle,System.Windows.Forms.DataGridViewAdvancedBorderStyle,System.Windows.Forms.DataGridViewPaintParts)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "level", Scope = "member", Target = "AdvancedDataGridView.TreeGridCell.#Paint(System.Drawing.Graphics,System.Drawing.Rectangle,System.Drawing.Rectangle,System.Int32,System.Windows.Forms.DataGridViewElementStates,System.Object,System.Object,System.String,System.Windows.Forms.DataGridViewCellStyle,System.Windows.Forms.DataGridViewAdvancedBorderStyle,System.Windows.Forms.DataGridViewPaintParts)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Un", Scope = "member", Target = "AdvancedDataGridView.TreeGridCell.#UnSited()")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "AdvancedDataGridView.TreeGridColumn.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#_isFirstSibling")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#_isLastSibling")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#Index")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#Nodes")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "value", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#Nodes")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#UniqueValue")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Un", Scope = "member", Target = "AdvancedDataGridView.TreeGridNode.#UnSited()")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#CopyTo(AdvancedDataGridView.TreeGridNode[],System.Int32)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#Item[System.Int32]")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.ICollection.CopyTo(System.Array,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.ICollection.IsSynchronized")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.ICollection.IsSynchronized")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.ICollection.IsSynchronized")]
[assembly: SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.ICollection.SyncRoot")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.ICollection.SyncRoot")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.ICollection.SyncRoot")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.IList.IsFixedSize")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "AdvancedDataGridView.TreeGridNodeCollection.#System.Collections.IList.Item[System.Int32]")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#DataMember")]
[assembly: SuppressMessage("Microsoft.Design", "CA1061:DoNotHideBaseClassMethods", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#DataMember")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "value", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#DataMember")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#DataSource")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "value", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#DataSource")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "_root", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#Dispose(System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#GetNodeForRow(System.Windows.Forms.DataGridViewRow)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#OnNodeCollapsed(AdvancedDataGridView.CollapsedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#OnNodeExpanded(AdvancedDataGridView.ExpandedEventArgs)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Un", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#UnSiteAll()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Un", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#UnSiteNode(AdvancedDataGridView.TreeGridNode)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#VirtualMode")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "value", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#VirtualMode")]
[assembly: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#NodeExpanded")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "AdvancedDataGridView.TreeGridView+Win32Helper.#PostMessage(System.Runtime.InteropServices.HandleRef,System.Int32,System.IntPtr,System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "AdvancedDataGridView.TreeGridView+Win32Helper.#SendMessage(System.Runtime.InteropServices.HandleRef,System.Int32,System.IntPtr,System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "AdvancedDataGridView.TreeGridView.#NodeCollapsed")]
