//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.ComponentModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PagedCollectionViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagedCollectionViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ComponentModel.PagedCollectionView.PagedCollectionViewResources", typeof(PagedCollectionViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added item does not appear at given index &apos;{0}&apos;..
        /// </summary>
        internal static string AddedItemNotAtIndex {
            get {
                return ResourceManager.GetString("AddedItemNotAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection Add event refers to item that does not belong to collection..
        /// </summary>
        internal static string AddedItemNotInCollection {
            get {
                return ResourceManager.GetString("AddedItemNotInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelEdit is not supported for the current edit item..
        /// </summary>
        internal static string CancelEditNotSupported {
            get {
                return ResourceManager.GetString("CancelEditNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing the NewItem placeholder is not allowed..
        /// </summary>
        internal static string CannotEditPlaceholder {
            get {
                return ResourceManager.GetString("CannotEditPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Filter property cannot be set when the &apos;CanFilter&apos; property returns false..
        /// </summary>
        internal static string CannotFilter {
            get {
                return ResourceManager.GetString("CannotFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; index in collection change event is not valid for collection of size &apos;{1}&apos;..
        /// </summary>
        internal static string CollectionChangeIndexOutOfRange {
            get {
                return ResourceManager.GetString("CollectionChangeIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing items is not supported by the IEditableCollection..
        /// </summary>
        internal static string EditItemNotSupportedByEditableCollection {
            get {
                return ResourceManager.GetString("EditItemNotSupportedByEditableCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was modified; enumeration operation may not execute..
        /// </summary>
        internal static string EnumeratorVersionChanged {
            get {
                return ResourceManager.GetString("EnumeratorVersionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compare two elements in the array..
        /// </summary>
        internal static string FailedToCompareElements {
            get {
                return ResourceManager.GetString("FailedToCompareElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex must be non-negative and less than the number of existing pages..
        /// </summary>
        internal static string InvalidPageIndex {
            get {
                return ResourceManager.GetString("InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSize cannot be a negative value..
        /// </summary>
        internal static string InvalidPageSize {
            get {
                return ResourceManager.GetString("InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property named &apos;{1}&apos; cannot be accessed because &apos;{0}&apos; returned a null reference. .
        /// </summary>
        internal static string InvalidPropertyAccess {
            get {
                return ResourceManager.GetString("InvalidPropertyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortDescription&apos;s property name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidPropertyName {
            get {
                return ResourceManager.GetString("InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change or check the contents or Current position of the PagedCollectionView while Refresh is being deferred..
        /// </summary>
        internal static string NoCheckOrChangeWhenDeferred {
            get {
                return ResourceManager.GetString("NoCheckOrChangeWhenDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not allowed during an AddNew or EditItem transaction..
        /// </summary>
        internal static string OperationNotAllowedDuringAddOrEdit {
            get {
                return ResourceManager.GetString("OperationNotAllowedDuringAddOrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not allowed during a transaction begun by &apos;{1}&apos;..
        /// </summary>
        internal static string OperationNotAllowedDuringTransaction {
            get {
                return ResourceManager.GetString("OperationNotAllowedDuringTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not allowed for this view..
        /// </summary>
        internal static string OperationNotAllowedForView {
            get {
                return ResourceManager.GetString("OperationNotAllowedForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property named &apos;{0}&apos; cannot be found on type &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property named &apos;{0}&apos; on type &apos;{1}&apos; cannot be read..
        /// </summary>
        internal static string PropertyNotReadable {
            get {
                return ResourceManager.GetString("PropertyNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property named &apos;{0}&apos; on type &apos;{1}&apos; cannot be written..
        /// </summary>
        internal static string PropertyNotWritable {
            get {
                return ResourceManager.GetString("PropertyNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Remove event must specify item position..
        /// </summary>
        internal static string RemovedItemNotFound {
            get {
                return ResourceManager.GetString("RemovedItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove/RemoveAt is not supported..
        /// </summary>
        internal static string RemoveNotSupported {
            get {
                return ResourceManager.GetString("RemoveNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the NewItem placeholder is not allowed..
        /// </summary>
        internal static string RemovingPlaceholder {
            get {
                return ResourceManager.GetString("RemovingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected collection change action &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedCollectionChangeAction {
            get {
                return ResourceManager.GetString("UnexpectedCollectionChangeAction", resourceCulture);
            }
        }
    }
}
