//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Navigation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Navigation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal cannot go back when CanGoBack equals false..
        /// </summary>
        internal static string Journal_CannotGoBack {
            get {
                return ResourceManager.GetString("Journal_CannotGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journal cannot go forward when CanGoForward equals false..
        /// </summary>
        internal static string Journal_CannotGoForward {
            get {
                return ResourceManager.GetString("Journal_CannotGoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Journal cannot navigate browser when UriFragmentHelper.IsEnabled equals false..
        /// </summary>
        internal static string Journal_NavigateBrowserFailed {
            get {
                return ResourceManager.GetString("Journal_NavigateBrowserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go back when CanGoBack equals false.
        /// </summary>
        internal static string NavigationService_CannotGoBack {
            get {
                return ResourceManager.GetString("NavigationService_CannotGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go forward when CanGoForward equals false.
        /// </summary>
        internal static string NavigationService_CannotGoForward {
            get {
                return ResourceManager.GetString("NavigationService_CannotGoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JournalOwnership can only be set to UsesParentJournal if this is a top-level Frame..
        /// </summary>
        internal static string NavigationService_JournalOwnership_UsesParentJournal_OnlyTopLevel {
            get {
                return ResourceManager.GetString("NavigationService_JournalOwnership_UsesParentJournal_OnlyTopLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation to a null Uri is not supported.
        /// </summary>
        internal static string NavigationService_NavigationToANullUriIsNotSupported {
            get {
                return ResourceManager.GetString("NavigationService_NavigationToANullUriIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation is only supported to relative Uri&apos;s that are fragments, or begin with &apos;/&apos; or which contain &apos;;component/&apos;.
        /// </summary>
        internal static string NavigationService_UriNotNavigable {
            get {
                return ResourceManager.GetString("NavigationService_UriNotNavigable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to load local XAML with an invalid syntax.  When a &apos;;component/&apos; is present, it must have the assembly name on the left side, and the page path and name on the right..
        /// </summary>
        internal static string PageResourceContentLoader_InvalidComponentSyntax {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_InvalidComponentSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML was found at the location &apos;{0}&apos;.
        /// </summary>
        internal static string PageResourceContentLoader_NoXAMLWasFound {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_NoXAMLWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos;, specified in the x:Class of &apos;{1}&apos; could not be found in any loaded assembly..
        /// </summary>
        internal static string PageResourceContentLoader_TheTypeSpecifiedInTheXClassCouldNotBeFound {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_TheTypeSpecifiedInTheXClassCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML at location &apos;{0}&apos; was unloadable..
        /// </summary>
        internal static string PageResourceContentLoader_XAMLWasUnloadable {
            get {
                return ResourceManager.GetString("PageResourceContentLoader_XAMLWasUnloadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register BrowserNavigationProxy.  Exception: {0}.
        /// </summary>
        internal static string UriFragmentHelper_BrowserNavigationProxy_RegistrationFailed {
            get {
                return ResourceManager.GetString("UriFragmentHelper_BrowserNavigationProxy_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UriFragmentHelper is unavailable because the HTML bridge is disabled. Please ensure your Silverlight instance has script access.  For more information, see http://msdn.microsoft.com/en-us/library/system.windows.browser.htmlpage.isenabled(VS.95).aspx..
        /// </summary>
        internal static string UriFragmentHelper_HtmlBridgeDisabled {
            get {
                return ResourceManager.GetString("UriFragmentHelper_HtmlBridgeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UriFragmentHelper is unable to navigate to the Uri fragment provided because doing so would violate the maximum Uri length restriction of 2048 characters..
        /// </summary>
        internal static string UriFragmentHelper_MaximumUriLength {
            get {
                return ResourceManager.GetString("UriFragmentHelper_MaximumUriLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UriMapper must not have a null UriMappingCollection..
        /// </summary>
        internal static string UriMapper_MustNotHaveANullUriMappingCollection {
            get {
                return ResourceManager.GetString("UriMapper_MustNotHaveANullUriMappingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MappedUri template must be specified..
        /// </summary>
        internal static string UriMapping_MappedUriTemplateMustBeSpecified {
            get {
                return ResourceManager.GetString("UriMapping_MappedUriTemplateMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri template cannot contain the same identifier more than once..
        /// </summary>
        internal static string UriMapping_UriTemplateCannotContainTheSameIdentifierMoreThanOnce {
            get {
                return ResourceManager.GetString("UriMapping_UriTemplateCannotContainTheSameIdentifierMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri template cannot have a fragment..
        /// </summary>
        internal static string UriMapping_UriTemplateCannotHaveAFragment {
            get {
                return ResourceManager.GetString("UriMapping_UriTemplateCannotHaveAFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri template cannot have a query string..
        /// </summary>
        internal static string UriMapping_UriTemplateCannotHaveAQueryString {
            get {
                return ResourceManager.GetString("UriMapping_UriTemplateCannotHaveAQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri template must be specified..
        /// </summary>
        internal static string UriMapping_UriTemplateMustBeSpecified {
            get {
                return ResourceManager.GetString("UriMapping_UriTemplateMustBeSpecified", resourceCulture);
            }
        }
    }
}
