// (c) Copyright Microsoft Corporation.
// This source is subject to [###LICENSE_NAME###].
// Please see [###LICENSE_LINK###] for details.
// All other rights reserved.
//
// <autogenerated />
// The Visual Studio metadata is not subjected to same source analysis

using System;
using System.Collections.Generic;
using System.Text;

namespace Microsoft.VisualStudio.TestTools.UnitTesting
{
    /// <summary>
    /// Verifiable interface.
    /// </summary>
	public interface IVerifiable
	{
        /// <summary>
        /// The IsValid method.
        /// </summary>
        /// <returns>Returns a value.</returns>
		bool IsValid();
	}
}