// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.
// <auto-generated />
// No style analysis for imported project.

namespace System.Windows.Controls.Samples.SyntaxHighlighting
{
    internal interface ILanguageCompiler
    {
        CompiledLanguage Compile(ILanguage language);
    }
}