//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.DataVisualization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.DataVisualization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the Chart&apos;s Axes property is not supported; changes to the collection should be made with its .Add/.Remove methods instead..
        /// </summary>
        internal static string Chart_Axes_SetterNotSupported {
            get {
                return ResourceManager.GetString("Chart_Axes_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis location cannot be changed to auto when hosted inside of a series host..
        /// </summary>
        internal static string Chart_AxisLocationChanged_CantBeChangedToAutoWhenHostedInsideOfASeriesHost {
            get {
                return ResourceManager.GetString("Chart_AxisLocationChanged_CantBeChangedToAutoWhenHostedInsideOfASeriesHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the Chart&apos;s Series property is not supported; changes to the collection should be made with its .Add/.Remove methods instead..
        /// </summary>
        internal static string Chart_Series_SetterNotSupported {
            get {
                return ResourceManager.GetString("Chart_Series_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned dependent axis cannot be used.  The data may not be able to be rendered on the provided axis or the series may require that they axis has an origin..
        /// </summary>
        internal static string DataPointSeriesWithAxes_GetAxes_AssignedDependentAxisCannotBeUsed {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_GetAxes_AssignedDependentAxisCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned independent axis cannot be used..
        /// </summary>
        internal static string DataPointSeriesWithAxes_GetAxes_AssignedIndependentAxisCannotBeUsed {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_GetAxes_AssignedIndependentAxisCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable axis is available for plotting the dependent value..
        /// </summary>
        internal static string DataPointSeriesWithAxes_NoSuitableAxisAvailableForPlottingDependentValue {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_NoSuitableAxisAvailableForPlottingDependentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This series does not support radial axes..
        /// </summary>
        internal static string DataPointSeriesWithAxes_ThisSeriesDoesNotSupportRadialAxes {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_ThisSeriesDoesNotSupportRadialAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine the size of an axis without an orientation..
        /// </summary>
        internal static string DisplayAxis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone {
            get {
                return ResourceManager.GetString("DisplayAxis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to set Edge property to an invalid value..
        /// </summary>
        internal static string EdgePanel_OnEdgePropertyChanged {
            get {
                return ResourceManager.GetString("EdgePanel_OnEdgePropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value must be larger than or equal to the minimum value..
        /// </summary>
        internal static string Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue {
            get {
                return ResourceManager.GetString("Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot read the Maximum of an empty range.&quot;.
        /// </summary>
        internal static string Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot read the Minimum of an empty range.&quot;.
        /// </summary>
        internal static string Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}].
        /// </summary>
        internal static string Range_ToString_Data {
            get {
                return ResourceManager.GetString("Range_ToString_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data..
        /// </summary>
        internal static string Range_ToString_NoData {
            get {
                return ResourceManager.GetString("Range_ToString_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value must be larger than or equal to the minimum value..
        /// </summary>
        internal static string RangeAxis_MaximumValueMustBeLargerThanOrEqualToMinimumValue {
            get {
                return ResourceManager.GetString("RangeAxis_MaximumValueMustBeLargerThanOrEqualToMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value must be smaller than or equal to the maximum value..
        /// </summary>
        internal static string RangeAxis_MinimumValueMustBeLargerThanOrEqualToMaximumValue {
            get {
                return ResourceManager.GetString("RangeAxis_MinimumValueMustBeLargerThanOrEqualToMaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is read-only..
        /// </summary>
        internal static string ReadOnlyObservableCollection_CollectionIsReadOnly {
            get {
                return ResourceManager.GetString("ReadOnlyObservableCollection_CollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series {0}.
        /// </summary>
        internal static string Series_OnGlobalSeriesIndexPropertyChanged_UntitledSeriesFormatString {
            get {
                return ResourceManager.GetString("Series_OnGlobalSeriesIndexPropertyChanged_UntitledSeriesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A series cannot be added to more than one series host..
        /// </summary>
        internal static string Series_SeriesHost_SeriesHostPropertyNotNull {
            get {
                return ResourceManager.GetString("Series_SeriesHost_SeriesHostPropertyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to remove permanent axis from axis collection..
        /// </summary>
        internal static string SeriesHostAxesCollection_InvalidAttemptToRemovePermanentAxisFromSeriesHost {
            get {
                return ResourceManager.GetString("SeriesHostAxesCollection_InvalidAttemptToRemovePermanentAxisFromSeriesHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An axis cannot be removed from a series host when one or more hosted series is listening to it..
        /// </summary>
        internal static string SeriesHostAxesCollection_RemoveItem_AxisCannotBeRemovedFromASeriesHostWhenOneOrMoreSeriesAreListeningToIt {
            get {
                return ResourceManager.GetString("SeriesHostAxesCollection_RemoveItem_AxisCannotBeRemovedFromASeriesHostWhenOneOrMo" +
                        "reSeriesAreListeningToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reset a style enumerator.  Reset style dispenser instead..
        /// </summary>
        internal static string StyleEnumerator_CantResetEnumeratorResetStyleDispenserInstead {
            get {
                return ResourceManager.GetString("StyleEnumerator_CantResetEnumeratorResetStyleDispenserInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to insert a duplicate item..
        /// </summary>
        internal static string UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem {
            get {
                return ResourceManager.GetString("UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem", resourceCulture);
            }
        }
    }
}
