//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4900
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.ComponentModel.DataAnnotations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataAnnotationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ComponentModel.DataAnnotations.Resources.DataAnnotationsResources", typeof(DataAnnotationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The associated metadata type for type &apos;{0}&apos; contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type..
        /// </summary>
        internal static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be public..
        /// </summary>
        internal static string AttributeStore_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("AttributeStore_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not contain a public method named &apos;{1}&apos;..
        /// </summary>
        internal static string AttributeStore_Unknown_Method {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;..
        /// </summary>
        internal static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must return a Boolean..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Must_Return_Bool {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; does not exist in type &apos;{1}&apos; or is not public and static (or Shared in Visual Basic)..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute.Method was not specified..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must declare an input parameter for the value..
        /// </summary>
        internal static string CustomValidationAttribute_Must_Accept_At_Least_One_Param {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Must_Accept_At_Least_One_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; requires 3 parameters: the object, a ValidationContext and a ValidationResult parameter that will be updated with the validation result.  (In C#, this last parameter must be an &quot;out&quot; parameter. In Visual Basic, this last parameter must be passed using &quot;ByRef&quot;.).
        /// </summary>
        internal static string CustomValidationAttribute_Short_Form_Not_Supported {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Short_Form_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom validation type &apos;{0}&apos; must be public..
        /// </summary>
        internal static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        internal static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute.ValidatorType was not specified..
        /// </summary>
        internal static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; does not have the correct signature.  It should declare 3 parameters: the object to be validated, a ValidationContext, and a parameter to receive a ValidationResult.   (In C#, this last parameter must be an &quot;out&quot; parameter. In Visual Basic, this last parameter must be passed using &quot;ByRef&quot;.).
        /// </summary>
        internal static string CustomValidationAttribute_Wrong_Parameters {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Wrong_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom DataType string cannot be null or empty..
        /// </summary>
        internal static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AutoGenerateField property has not been set. Use the GetAutoGenerateField method to get the value..
        /// </summary>
        internal static string DisplayAttribute_AutoGenerateFieldNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_AutoGenerateFieldNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AutoGenerateFilter property has not been set. Use the GetAutoGenerateFilter method to get the value..
        /// </summary>
        internal static string DisplayAttribute_AutoGenerateFilterNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_AutoGenerateFilterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type provided for EnumDataTypeAttribute cannot be null..
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; needs to represent an enumeration type..
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve property &apos;{0}&apos; because localization failed.  Type &apos;{1}&apos; is not public or does not contain a public static string property with the name &apos;{2}&apos;..
        /// </summary>
        internal static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetadataClassType cannot be null..
        /// </summary>
        internal static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; requires {1} parameters..
        /// </summary>
        internal static string Method_Parameter_Count_Wrong {
            get {
                return ResourceManager.GetString("Method_Parameter_Count_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for parameter &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        internal static string Parameter_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Parameter_Value_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for property &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        internal static string Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Property_Value_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must implement {1}..
        /// </summary>
        internal static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value &apos;{0}&apos; must be greater than or equal to the minimum value &apos;{1}&apos;..
        /// </summary>
        internal static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum and maximum values must be set,.
        /// </summary>
        internal static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OperandType must be set when strings are used for minimum and maximum values..
        /// </summary>
        internal static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        internal static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must match the regular expression &apos;{1}&apos;..
        /// </summary>
        internal static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pattern must be set to a valid regular expression..
        /// </summary>
        internal static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length must be a nonnegative integer..
        /// </summary>
        internal static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        internal static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &apos;{1}&apos; is not a string. Every key control parameter must be a string..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} is null. Every key control parameter must be a string..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &apos;{1}&apos; occurs more than once..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of control parameters must be even..
        /// </summary>
        internal static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either ErrorMessageString or ErrorMessageResourceName must be set, but not both..
        /// </summary>
        internal static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute..
        /// </summary>
        internal static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on resource type &apos;{1}&apos; is not a string type..
        /// </summary>
        internal static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type &apos;{0}&apos; does not have a publicly visible static property named &apos;{1}&apos;..
        /// </summary>
        internal static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is invalid..
        /// </summary>
        internal static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ValidationContext for the type &apos;{0}&apos;, member name &apos;{1}&apos; must provide the MethodInfo..
        /// </summary>
        internal static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of type &apos;{0}&apos; already exists in the container..
        /// </summary>
        internal static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance provided must match the ObjectInstance on the ValidationContext supplied..
        /// </summary>
        internal static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
    }
}
