// (c) Copyright Microsoft Corporation.
// This source is subject to [###LICENSE_NAME###].
// Please see [###LICENSE_LINK###] for details.
// All other rights reserved.
//
// <auto-generated /> 
// The Visual Studio metadata is not subjected to same source analysis

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight")]
[assembly: AssemblyDescription("Visual Studio Unit Testing Metadata")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyProduct("Microsoft.Silverlight.Testing")]
[assembly: AssemblyCopyright("Copyright © 2009 Microsoft Corporation")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: ComVisible(false)]
[assembly: Guid("6da89083-5f07-42fe-a9c1-5833ebfcc89b")]
[assembly: AssemblyVersion("5.0.5.0")]
[assembly: AssemblyFileVersion("5.0.60818.0")]
